Allow configure to pass when cross compiling

diff --git a/auto/feature b/auto/feature
--- a/auto/feature
+++ b/auto/feature
@@ -53,7 +53,13 @@ if [ -x $NGX_AUTOTEST ]; then
 
         yes)
             # /bin/sh is used to intercept "Killed" or "Abort trap" messages
-            if /bin/sh -c $NGX_AUTOTEST >> $NGX_AUTOCONF_ERR 2>&1; then
+            if test -n "$NGX_CROSSCOMPILING"; then
+                echo " found (cross compiling so cannot run)"
+                ngx_found=yes
+                if test -n "$ngx_feature_name"; then
+                    have=$ngx_have_feature . auto/have
+                fi
+            elif /bin/sh -c $NGX_AUTOTEST >> $NGX_AUTOCONF_ERR 2>&1; then
                 echo " found"
                 ngx_found=yes
 
@@ -67,6 +73,10 @@ if [ -x $NGX_AUTOTEST ]; then
         ;;
 
         value)
+            if test -n "$NGX_CROSSCOMPILING"; then
+                echo " Cannot check due to cross compiling!"
+                exit 1
+            fi
             # /bin/sh is used to intercept "Killed" or "Abort trap" messages
             if /bin/sh -c $NGX_AUTOTEST >> $NGX_AUTOCONF_ERR 2>&1; then
                 echo " found"
@@ -85,6 +95,10 @@ END
         ;;
 
         bug)
+            if test -n "$NGX_CROSSCOMPILING"; then
+                echo " Cannot check due to cross compiling!"
+                exit 1
+            fi
             # /bin/sh is used to intercept "Killed" or "Abort trap" messages
             if /bin/sh -c $NGX_AUTOTEST >> $NGX_AUTOCONF_ERR 2>&1; then
                 echo " not found"
diff --git a/auto/os/freebsd b/auto/os/freebsd
--- a/auto/os/freebsd
+++ b/auto/os/freebsd
@@ -18,16 +18,25 @@ ngx_spacer='
 # __FreeBSD_version is used for the testing of the build environment.
 # sysctl kern.osreldate is used for the testing of the kernel capabilities.
 
-version=`grep "#define __FreeBSD_version" /usr/include/osreldate.h \
+version=`grep "#define __FreeBSD_version" "${NGX_SYSROOT}/usr/include/osreldate.h" \
          | sed -e 's/^.* \(.*\)$/\1/'`
 
-osreldate=`/sbin/sysctl -n kern.osreldate`
+if test -z "$version"; then
+    echo "FATAL: Cannot determine FreeBSD version from ${NGX_SYSROOT}/usr/include/osreldate.h"
+    exit 1
+fi
+
+if test -n "$NGX_CROSSCOMPILING"; then
+    osreldate=$version
+else
+    osreldate=`/sbin/sysctl -n kern.osreldate`
+fi
 
 
 # setproctitle() in libutil
 
-if [ \( $version -ge 500000 -a $version -lt 500012 \) \
-     -o $version -lt 410002 ]
+if [ \( "$version" -ge 500000 -a "$version" -lt 500012 \) \
+     -o "$version" -lt 410002 ]
 then
     echo " + setproctitle() in libutil"
 
diff --git a/auto/types/sizeof b/auto/types/sizeof
--- a/auto/types/sizeof
+++ b/auto/types/sizeof
@@ -40,8 +40,19 @@ eval "$ngx_test >> $NGX_AUTOCONF_ERR 2>&1"
 
 
 if [ -x $NGX_AUTOTEST ]; then
-    ngx_size=`$NGX_AUTOTEST`
-    echo " $ngx_size bytes"
+    size_var="NGX_SIZEOF_$ngx_type"
+    size_var=`echo "NGX_SIZEOF_$ngx_type" | tr -s ' ' | tr ' ' '_' | tr '*' 'p'`
+    eval "size_var_value=\$$size_var"
+    if test -n "$size_var_value"; then
+        ngx_size="$size_var_value"
+        echo " $ngx_size bytes"
+    elif test -n "$NGX_CROSSCOMPILING"; then
+        echo " cannot detect size of $ngx_type when cross compiling, you must set \$$size_var!"
+        exit 1
+    else
+        ngx_size=`$NGX_AUTOTEST`
+        echo " $ngx_size bytes"
+    fi
 fi
 
 
@@ -51,7 +62,7 @@ case $ngx_size in
         ngx_max_len='(sizeof("-2147483648") - 1)'
     ;;
 
-    8)
+    8|16|32)
         ngx_max_value=9223372036854775807LL
         ngx_max_len='(sizeof("-9223372036854775808") - 1)'
     ;;
